<?php
return [
    //不需要登录可操作性的方法
    'noLogin'=>[
      'User/login',
      'Msg/sendregister',
      'Msg/sendfindpassoword',
        //新闻首页
        'News/index',
        //定位
        'News/location',
        //新闻详情
        'News/detail',
        //新闻详情
        'News/ListCity',
    ],
    //需要验证权限的方法
   'check'=>[
    'Index/index',
    'User/logout',
   ],
];